package oyg.sudoku;
/*
 * MainForm.java
 *
 * Created on 1 יולי 2005, 11:23
 */



/**
 *
 * @author  oyagev
 */
import java.lang.*;

public class MainForm extends javax.swing.JFrame {
    
    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }
    public int getNumberSelected(){
        return numSelected;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        
        
        
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        ExitMenuItem = new javax.swing.JMenuItem();
        GameMenu = new javax.swing.JMenu();
        NewGameMenuItem = new javax.swing.JMenuItem();
        CheckMenuItem = new javax.swing.JMenuItem();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextPane1 = new javax.swing.JTextPane();
        
        numToggleButton = new javax.swing.JToggleButton[9];
        int i=1,j=1,counter=0;
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku!");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        setBounds(130,100,-1,-1);
        
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            /*public void keyTyped(java.awt.event.KeyEvent evt) {
                KeyboardTyped(evt);
            }*/
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyboardPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        for (i=0;i<3;i++){
            for (j=0;j<3;j++){
                numToggleButton[counter] = new javax.swing.JToggleButton();
                numToggleButton[counter].setFont(new java.awt.Font("Dialog", 1, 30));
                numToggleButton[counter].setText(String.valueOf(counter+1));
                numToggleButton[counter].setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                numToggleButton[counter].setMargin(new java.awt.Insets(0, 0, 0, 0));
                if (counter ==0){
                    numToggleButton[counter].setSelected(true);
                }
                numToggleButton[counter].addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                jToggleButton1ActionPerformed(evt);
                                                }
                                            });
                numToggleButton[counter].addKeyListener(new java.awt.event.KeyAdapter() {
                                            /*public void keyTyped(java.awt.event.KeyEvent evt) {
                                                KeyboardTyped(evt);
                                            }*/
                                            public void keyPressed(java.awt.event.KeyEvent evt) {
                                                KeyboardPressed(evt);
                                            }
                                        });
                jPanel1.add(numToggleButton[counter], new org.netbeans.lib.awtextra.AbsoluteConstraints(20+j*40, 20+i*40, 40, 40));
                counter++;
            }
        }
        jSlider1.setMaximum(50);
        jSlider1.setMinimum(8);
        jSlider1.setValue(30);
        jSlider1.setPreferredSize(new java.awt.Dimension(140, 16));
        jPanel1.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel1.setText("Difficulty:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel2.setText("Low");
        //jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        //jLabel2.setAlignmentY(0.0F);
        
        jLabel2.setPreferredSize(new java.awt.Dimension(35, 20));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel3.setText("High");
        jLabel3.setPreferredSize(new java.awt.Dimension(35, 20));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setBorder(new javax.swing.border.EtchedBorder());
        jTextPane1.setText("");
        jPanel1.add(jTextPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 230, 159, -1));

        
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 250));

        FileMenu.setLabel("File");
        ExitMenuItem.setLabel("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });

        FileMenu.add(ExitMenuItem);

        jMenuBar1.add(FileMenu);

        GameMenu.setLabel("Game");
        GameMenu.setName("GameMenu");
        NewGameMenuItem.setLabel("New Game");
        GameMenu.add(NewGameMenuItem);
        NewGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });

        CheckMenuItem.setLabel("Check!");
        GameMenu.add(CheckMenuItem);
        CheckMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMenuItemActionPerformed(evt);
            }
        });

        jMenuBar1.add(GameMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>
    private void KeyboardPressed(java.awt.event.KeyEvent evt) {
// TODO add your handling code here:
        char pressedKey = evt.getKeyChar();
        int numSelected;
        numSelected = (int)pressedKey-48;
        if (numSelected>=1 && numSelected<=9){
            setNumSelected(numSelected);
        }
        
    }
    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {                                              
// TODO add your handling code here:
        jTextPane1.setText("");
        initiatorObject.NewGame(this.getDifficulty());
    } 
    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {                                              
// TODO add your handling code here:
        System.exit(0);
    }                                             
    private void checkMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                              
// TODO add your handling code here:
        if(sodukoObject.CheckSodukoBoard()){
            jTextPane1.setText("You are a Genius!");
            System.out.println("You are a Genius!");
        }
        else{
            jTextPane1.setText("I don't think so...");
            System.out.println("Doooo!!!");
        }
    } 
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
/*        int i=0;
        for (i=0;i<9;i++){
            numToggleButton[i].setSelected(false);
        }
        ((javax.swing.JToggleButton)evt.getSource()).setSelected(true);*/
        numSelected = Integer.parseInt (((javax.swing.JToggleButton)evt.getSource()).getText());
        setNumSelected(numSelected);
    }
    public void setNumSelected(int num){
        int i=0;
        for (i=0;i<numToggleButton.length;i++){
            if (Integer.parseInt(numToggleButton[i].getText())==num){
                numToggleButton[i].setSelected(true);
                numSelected = num;
            }
            else{
                numToggleButton[i].setSelected(false);
            }
        }
    }
    public void setSodukobject(Soduko newSodukoObject){
        sodukoObject = newSodukoObject;
    }
    public void setInitiatorObject(CreateSudokuGUI newInitiatorObject){
        initiatorObject = newInitiatorObject;
    }
    public int getDifficulty(){
        return (int)jSlider1.getValue();
    }
    
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify
    private javax.swing.JMenuItem CheckMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu GameMenu;
    private javax.swing.JMenuItem NewGameMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton[] numToggleButton;
    private int numSelected = 1;
    private Soduko sodukoObject;
    private CreateSudokuGUI initiatorObject;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextPane jTextPane1;
    /*private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;*/
    // End of variables declaration
    
}
